### ISSUE TITLE
Leave room with runtime error: Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ctc316** [kataras/go-websocket#13]
Here is the problem I've encountered. Checked out the leaveRoom function. No Idea why this happened.

![1](https://cloud.githubusercontent.com/assets/8285764/19953350/ce43eef0-a1a7-11e6-820d-954be34cdb43.png)

**Comment by ghost** [comment]
Try to remove your `$GOPATH/github.com/kataras/go-websocket` and upgrade it with `go get -u github.com/kataras/go-websocket`.

**Comment by anykao** [comment]
I think I have the latest version and got the same panic
![image](https://cloud.githubusercontent.com/assets/1076537/21302265/cfbcdd94-c5f8-11e6-913f-5e062d8b5eab.png)
