### ISSUE TITLE
How to use this package to build a golang client?

### ISSUE THREAD

**Issue by dxvgef** [kataras/go-websocket#19]
I used go-websocket to build a websocket server, but I used its `Join()` function, it is not compatible with other websocket clients, go-websocket can build the client? I only found its JS client, I want to use it to create a golang client

**Comment by dxvgef** [comment]
The code snippet that triggers the bug:

```Go
	client.On("queue", func(msg string) {
		client.Emit("queue", "auth:success")
		/*
		//If you delete the comments of this code, this problem will occur
		go func() {
			for {
				client.Emit("online", time.Now().Unix())
				time.Sleep(3 * time.Second)
			}
		}()
		*/
	})
```

**Comment by ghost** [comment]
You can connect a client using [its](https://github.com/gorilla/websocket) underline websocket package, currently the kataras/go-websocket supports only javascript client-side library.

**Comment by ghost** [comment]
@dxvgef Here you're 

An example of this using the `/x/net/websocket` package as the client.  See: https://github.com/kataras/go-websocket/issues/24#issuecomment-275708849
