### ISSUE TITLE
expose req *http.Request  to connection

### ISSUE THREAD

**Issue by notedit** [kataras/go-websocket#2]
so  we can do some auth use cookie and query param

**Comment by ghost** [comment]
Websocket are not the same as HTTP, you can do header-authentication only, otherwise just make a REST endpoint and take the user from there, pass these information to a websocket message from client to server

**Comment by notedit** [comment]
yes  but i need  get the http request header  in the connection.

i have used socketio,  socketio can handle this.

**Comment by ghost** [comment]
Make a PR as you said, I will approve it if it's correct, don't be afraid, go on, I will be happy!

**Comment by notedit** [comment]
ok

**Comment by notedit** [comment]
have a pr here  https://github.com/kataras/go-websocket/pull/3

**Comment by notedit** [comment]
i have another idea,   maybe  we could use a  Middleware

**Comment by ghost** [comment]
`req := c.Request()` . 

An Iris(v6) example: https://github.com/iris-contrib/examples/blob/master/websocket/main.go#L34
