### ISSUE TITLE
reconnect on disconnection

### ISSUE THREAD

**Issue by kickbox** [kataras/go-websocket#34]
How to reconnect the web socket from server on disconnection, without refreshing the client page?

**Comment by kickbox** [comment]
I think this question is better suited within the iris repo. Will close this and ask [there](https://github.com/kataras/iris/issues/1066).

**Comment by kataras** [comment]
https://github.com/kataras/neffos.js/blob/da16071b1966b866acac33fd42d136a61c7a696a/_examples/browser/index.html#L66
